### PR TITLE
bitECS Packed-5 example refactor

### PR DESCRIPTION
**Pull request by NateTheGreatt**
@ooflorent @stasm this is kind of nuts but...

I rewrote `bitecs` `packed_5` example in the style of `goodluck` and this happened:

Entity count = 1000
Before:
```
Packed (5 queries)
  bitecs: 27,015 op/s (±0.59%)
  goodluck: 157,549 op/s (±0.33%)
```

After:
```
Packed (5 queries)
  bitecs: 258,799 op/s (±0.80%)
  goodluck: 156,337 op/s (±0.52%)
```

I'm pretty amazed at the results, tbh.

### CODE REVIEW

**Comment by ooflorent** [comment]
To be honest I added `packed_5` especially to torture `bitECS` because `System#execute` suffers from polymorphism. While this change greatly improves the performance, I think it is a bit deceitful since you don't expect your users to write such code. If I'm wrong, I'll be happy to merge this PR, but could you also update the other cases?

I still think you should `System#update` by using codegen (or something else) to improve TurboFan optimizations.

```js
let executeTemplate = (
  system,
  localEntities,
  componentManagers,
  updateFn,
  before,
  after
) => (force) => {
  if (force || system.enabled) {
    if (before) before(...componentManagers);
    if (updateFn) {
      const to = system.count;
      for (let i = to - 1; i >= 0; i--) {
        const eid = localEntities[i];
        updateFn(eid);
      }
    }
    if (after) after(...componentManagers);
  }
};

let executeFactory = Function(`return ${executeTemplate.toString()}`)();

system.execute = executeFactory(
  system,
  localEntities,
  componentManagers,
  updateFn,
  before,
  after
);
```

**Comment by NateTheGreatt** [comment]
This PR wasn't necessarily created to be merged, it was created to discuss the results. This is very telling, and I think other ECS libraries could increase their performance with this knowledge. I tried using your `executeTemplate`, but it didn't seem to have any performance implications on my end.

I use `bitecs` in all sorts of different ways in our game engine, there are places where I have manually iterated and checked entities against the system, so I don't think it's deceitful to use a library in this way because the API was intended to fully support this, all of these pieces are documented. There is simply no soft-documentation to show this style, and the lifecycle hooks are meant to be the most convenient parts of the API. I hadn't realized that the polymorphism was so severe in the latest revisions.

More than that, with these results, I want to potentially change `bitecs` to reduce that polymorphism, or at least show how this style of writing system iteration logic has more performance benefits than I realized. I can't seem to find a way to wrap this iteration logic and still maintain the performance, and that's what I mainly want to discuss in this PR, for the benefit of both `bitecs` and all other ECS's.

I tried to wrap the system for-loops into simple functions last night:
```
  const { A, B, C, D, E } = world.registry.components

  function runA () {
    for (let i = 0; i < packed_a.localEntities.length; i++) {
      const eid = packed_a.localEntities[i];
      A.value[eid] *= 2;
    }
  }

  function runB () {
    for (let i = 0; i < packed_b.localEntities.length; i++) {
      const eid = packed_b.localEntities[i];
      B.value[eid] *= 2;
    }
  }
  
  function runC () {
    for (let i = 0; i < packed_c.localEntities.length; i++) {
      const eid = packed_c.localEntities[i];
      C.value[eid] *= 2;
    }
  }
  
  function runD () {
    for (let i = 0; i < packed_d.localEntities.length; i++) {
      const eid = packed_d.localEntities[i];
      D.value[eid] *= 2;
    }
  }
  
  function runE () {
    for (let i = 0; i < packed_e.localEntities.length; i++) {
      const eid = packed_e.localEntities[i];
      E.value[eid] *= 2;
    }
  }
  
  return () => {
    runA();
    runB();
    runC();
    runD();
    runE();
  };
  ```
  
One tiny layer of abstraction dropped performance down to `217,468 op/s`. If the for-loops are changed to `forEach` we see yet another performance drop down to the range of `156,643 op/s`. Quite a chonky hit.

So I'm curious, @ooflorent / @stasm , do either of you have any other ideas on how to wrap the iteration logic without the performance hit?

**Comment by NateTheGreatt** [comment]
When I have some time tonight I will be putting out `bitecs` `v0.2.0` with a change to the API that fixes this polymorphism performance issue:

```javascript
  world.registerSystem({
    name: "packed_a",
    components: ["A"],
    update: (entities, A) => {
      for (let i = 0; i < entities.length; i++) {
        const eid = entities[i];
        A.value[eid] *= 2
      }
    }
  });
  ```

I guess as long as the for loop is exposed to the scope in which it was declared it does not suffer from the perf hit.

**Comment by NateTheGreatt** [comment]
When I have some time tonight I will be putting out `bitecs` `v0.2.0` with a change to the API that fixes this polymorphism performance issue:

```javascript
  world.registerSystem({
    name: "packed_a",
    components: ["A"],
    update: (entities, A) => {
      for (let i = 0; i < entities.length; i++) {
        const eid = entities[i];
        A.value[eid] *= 2
      }
    }
  });
  ```

I guess as long as the for loop is not encapsulated it does not suffer from the perf hit.

**Comment by ooflorent** [comment]
FYI, I was able to gain a bit of perf on bitECS by rewrite `System#update`.

**Before:**
```
bitecs
  packed_1        147,526 op/s
  packed_5        23,342 op/s
  simple_iter     18,364 op/s
  frag_iter       251,261 op/s
```

**After:**
```
bitecs
  packed_1        155,722 op/s
  packed_5        109,256 op/s
  simple_iter     99,703 op/s
  frag_iter       304,003 op/s
  add_remove      929 op/s
```

However, **no library author** should use the tricks I used unless they are prepared to suffer maintaining it!
So, how did I do it? Using `Function`:

```js
const beforeFn = before
  ? Function(
      "f",
      ...componentDependencies,
      `return ()=>/*${Math.random()}*/f(${componentDependencies.join(",")})`
    )(before, ...componentManagers)
  : null;

const afterFn = after
  ? Function(
      "f",
      ...componentDependencies,
      `return ()=>/*${Math.random()}*/f(${componentDependencies.join(",")})`
    )(after, ...componentManagers)
  : null;

const updateFn = update
  ? Function(
      "f",
      "E",
      "I",
      `const g=(e,i)=>{I[e]=i;f(e)};` +
        `return ()=>/*${Math.random()}*/E.forEach(g)`
    )(
      update(...componentManagers),
      system.localEntities,
      system.entityIndexes
    )
  : null;

// Define execute function which executes each local entity
system.execute = (force) => {
  if (force || system.enabled) {
    if (beforeFn) beforeFn();
    if (updateFn) updateFn();
    if (afterFn) afterFn();
  }
};
```

I repeat, **do not do this**. Do not fall into this trap. `bitecs` is already super fast. **There is no point in crippling your codebase to _win_ a benchmark.**

**Comment by NateTheGreatt** [comment]
@ooflorent super fascinating! thanks for sharing that. I won't cripple my codebase to win a benchmark, but I _will_ cripple it to gain another few hundred CCU in my networking engine :D:D:D

**Comment by NateTheGreatt** [comment]
closing in favor of https://github.com/noctjs/ecs-benchmark/pull/30

**Pull request closed without merging**
