### PR TITLE
Update to goodluck 5.1.0

### PR DESCRIPTION
**Pull request by stasm**
This version brings an optimization from https://github.com/piesku/goodluck/issues/43 which avoids out-of-bounds access into `world.Signature` in `createEntity`.

### CODE REVIEW

**Comment by stasm** [comment]
Before:

```
Create and delete (entities: 4000)
  @jakeklassen/ecs: 102 op/s (±1.57%)
  ecsy: 166 op/s (±0.32%)
  ent-comp: 80 op/s (±1.06%)
  flock-ecs: 66 op/s (±24.65%)
  goodluck: 45 op/s (±0.40%)
  makr: 2,090 op/s (±0.34%)
  modecs: 3 op/s (±2.93%)
  perform-ecs: 372 op/s (±2.03%)
  picoes: 110 op/s (±4.11%)
  tiny-ecs: 101 op/s (±1.94%)

Update (entities: 4000, queries: 3)
  @jakeklassen/ecs: 2,155 op/s (±0.53%)
  ecsy: 1,970 op/s (±0.94%)
  ent-comp: 42,326 op/s (±13.61%)
  flock-ecs: 1,788 op/s (±2.72%)
  goodluck: 30,166 op/s (±0.72%)
  makr: 7,790 op/s (±0.28%)
  modecs: 1,598 op/s (±0.33%)
  perform-ecs: 42,508 op/s (±0.38%)
  picoes: 962 op/s (±0.36%)
  tiny-ecs: 36,992 op/s (±14.93%)
```

After:

```
Create and delete (entities: 4000)
  @jakeklassen/ecs: 106 op/s (±0.63%)
  ecsy: 174 op/s (±0.55%)
  ent-comp: 80 op/s (±0.94%)
  flock-ecs: 67 op/s (±24.80%)
  goodluck: 123 op/s (±0.86%)
  makr: 2,018 op/s (±0.56%)
  modecs: 3 op/s (±0.97%)
  perform-ecs: 361 op/s (±0.25%)
  picoes: 125 op/s (±4.48%)
  tiny-ecs: 100 op/s (±0.49%)

Update (entities: 4000, queries: 3)
  @jakeklassen/ecs: 2,141 op/s (±0.63%)
  ecsy: 1,946 op/s (±1.23%)
  ent-comp: 41,755 op/s (±14.56%)
  flock-ecs: 1,697 op/s (±2.05%)
  goodluck: 30,241 op/s (±0.70%)
  makr: 7,910 op/s (±0.31%)
  modecs: 1,667 op/s (±0.20%)
  perform-ecs: 38,417 op/s (±0.45%)
  picoes: 1,008 op/s (±0.38%)
  tiny-ecs: 35,792 op/s (±14.89%)
```

Sometimes, Goodluck scores ~103 op/s in the first benchmark. It's consistently either 103 or 123 for a few runs on my machine, actually.

**Comment by stasm** [comment]
@ooflorent Could you try running this on your machine? Or, feel free to push an update to the README directly to my branch, if it's easier for you.

**Comment by stasm** [comment]
@ooflorent It looks like on your machine the first benchmark only improved from 85 to 96? Any idea why?

**Comment by ooflorent** [comment]
I ran them on the latest node 14 stable release. If you look at the CI output the results went from 31op/s to 86op/s. I’m not really sure why the gap isn’t bigger... I tried to run the case multiple times but results are similar. 

However, I’ll update the benchmark suite to have explicit fixed rates. That would improve the consistency.

**Comment by stasm** [comment]
OK, thanks. Feel free to merge this at your convenience.

**Pull request merged**
