### PR TITLE
swapped modecs with bitecs

### PR DESCRIPTION
**Pull request by NateTheGreatt**
Hey there! First off, thanks for the repo. Much needed.

I noticed that it is benchmarking my old ECS library ModECS. This PR swaps that out for my new ECS library: bitECS!

It is far more feature rich, documented, and tops the benchmarks.

It should also be noted that bitECS is capable of handling many millions of entities at once. I would enjoy seeing a benchmark against the other libraries at that capacity :)

Cheers

### CODE REVIEW

**Comment by NateTheGreatt** [comment]
I'm not so sure these benchmarks are accurate. I pulled `perform-ecs` and benchmarked it side-by-side with `bitecs`, in completely separate files and separate runs. `bitecs` wins out on all metrics, creation/deletion and updates.

at 1 million entities, `perform-ecs` can do a full update in about `60ms` on my cpu.
meanwhile, `bitecs` can update 1 mill in about `1-2ms`. this is orders of magnitude faster.

**Comment by ooflorent** [comment]
> I'm not so sure these benchmarks are accurate. 
That something that should definitely be improved but I have yet to figure out how to fairly bench the implementations.

> might I suggest refactoring?
I would love to. Feel free to open a discussion or a draft PR!

**Review by ooflorent — CHANGES_REQUESTED** [review]
Could you keep the lockfile please?

**Comment by ooflorent** [comment]
@NateTheGreatt: I've rebased your PR but I have don't have write access on your fork (see #11).

**Pull request closed without merging**
